package com.bot.botconnector;

import com.bot.botconnector.util.MarkDownConverter;

public class TestApplication {
    public static void main(String[] args) {
        String creditCard = "<div onclick=\"window.inqFrame.Application.sendVALinkClicked(event);\">Ik begrijp dat je een vraag hebt over een creditcard. <br />Waar wil je iets over weten? <ul><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"433cd314-51c0-4eb7-9c2b-00c9bb807e2a\">Aanvragen en activeren</a></li><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"b8a9dcd1-ea8e-45cd-841e-d5b3a39ca00a\">Bezorgtijd</a></li><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"586645aa-6fcc-4b25-a3a2-4065033bff9a\">Kosten en voorwaarden</a></li><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"28732de9-dc51-499c-97f1-db019f743e9c\">Afschrijvingen, terug- en bijstorten</a></li><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"d1e7ce87-1312-4e42-a9c5-649ba75d8a3d\">Andere vraag</a></li></ul> <div class=\"nw_options_end\"></div></div>";
        String Bezorgtijd = "<div onclick=\"window.inqFrame.Application.sendVALinkClicked(event);\">We versturen je creditcard en pincode in aparte enveloppen, ongeveer 5 werkdagen na je aanvraag. Met spoed aanvragen kan helaas niet.<br /><br />Wacht je al meer dan 5 werkdagen op je creditcard? <ul><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"20139479-3507-432c-a2fc-6fb109f8ffea\">Ja</a></li><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"228d2501-d390-41e5-99a6-554824aaf79d\">Nee</a></li><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"443d4b18-f62f-4bb8-b600-76ac36e99a1d\">Weet ik niet</a></li></ul> <div class=\"nw_options_end\"></div></div>";

        String applePay = "<div onclick=\"window.inqFrame.Application.sendVALinkClicked(event);\">Met Apple Pay betaal je zonder extra kosten met je iPhone of Apple Watch. Je kunt je betaalpas en creditcard hiervoor gebruiken.<br /><br />Waarover gaat je vraag? <ul><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"a0ca3f8a-5bfc-428d-a48c-85120bdefc90\">Gebruiken</a></li><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"394928ef-afd7-4279-9a18-fab65e1a6070\">Verificatiecode</a></li><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"2db22765-8aaf-433b-b6e0-5419d3b7dab4\">Betaallimiet</a></li><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"42f77fd2-4ad1-4fd5-80b1-a065042eb66c\">Het werkt niet</a></li><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"02b5dced-fdfd-4599-9db8-f77416cf90f9\">Iets anders</a></li></ul> <div class=\"nw_options_end\"></div></div>";
        String VerificatieCode = "<div onclick=\"window.inqFrame.Application.sendVALinkClicked(event);\">Voor een verificatiecode moet je telefoonnummer bij ons bekend zijn. Je controleert en wijzigt dit in de Rabo App of internetbankieren op je computer.<hr />Is de verificatiecode verlopen? Verwijder dan al je passen en cards uit je Wallet en installeer ze opnieuw.<br /><br />Zo verwijder je alles:<ol><li>Ga naar &#39;Instellingen&#39; op je iPhone</li><li>Open &#39;Wallet en Apple Pay&#39;</li><li>Kies je oude pas / card en druk op &#39;Verwijder deze kaart&#39;</li><li>Herhaal dit voor iedere pas of card in je Wallet.</li></ol>Is het verwijderen gelukt? Installeer Apple Pay opnieuw. <ul><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"323c02b1-2a24-4274-b8eb-23d442d74f0f\">Check 06-nummer</a></li><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"0265df01-0063-4e63-98f4-bdf0dee51f12\">Installeer Apple Pay</a></li></ul> <div class=\"nw_options_end\"></div></div>";
        String installApplePay = "<div onclick=\"window.inqFrame.Application.sendVALinkClicked(event);\">Check of je 06-nummer bij ons bekend is en klopt:<br /><ul><li>Log in in internetbankieren of de Rabo App</li><li>Ga naar &#39;Profiel&#39; rechtsboven</li><li>Druk op je gebruikersnaam</li><li>Kies &#39;Contactgegevens wijzigen&#39;</li></ul>Hier staat je nummer. Klopt het niet? Pas het aan met het pennetje.<br /><button><a href=\"https://bankieren.rabobank.nl/bankierenplus/deeplinking/mijn-gegevens-beheren/start\" target=\"_blank\" data-vtz-browse=\"https://bankieren.rabobank.nl/bankierenplus/deeplinking/mijn-gegevens-beheren/start\" data-vtz-link-type=\"Web\" rel=\"noopener noreferrer\">Check 06-nummer</a></button><hr />Je wijziging is na een paar dagen actief. Daarna kun je Apple Pay installeren. \n<hr />Heb je zo een antwoord op je vraag? <ul><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"83c547b6-f2ac-4af9-b2e3-552a8e5deb0c\">Ja</a></li><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"295a9f46-6316-4d13-97df-e42a24534366\">Nee</a></li></ul> <div class=\"nw_options_end\"></div></div>";
        String html = "<div onclick=\"window.inqFrame.Application.sendVALinkClicked(event);\">This is the test intent created for testing the new markdown.<br />This sentence should start on a new line.<hr />This sentence should be in a new bubble. Let&#39;s check out hyperlinks now and firstly see if we can link to the That URL should go to the service page about retirement. Let&#39;s see if we can turn it into a button:<br><br><button><a href=\"https://www.rabobank.nl/particulieren/pensioen/service/\" target=\"_blank\">Go to retirement</a></button><br />Bullet List<br /><ul><li>Debit</li><li>Credit</li></ul><br />Number List<br /><ol><li>Debit</li><li>Credit</li></ol><br />The following link is a link within NIQS (a Jump Link) and should direct to <a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"4862644201448427386\" class=\"dialog\">Contactloos betalen</a>.<br /><br />Now, would you like to see a numbered list, bulleted list, the straightforward components or a jump link? <ul><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"9b7e734d-e6ca-45f9-8b87-9849d0019c75\">Numbered list</a></li><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"bb498cac-d7e9-464d-a340-877222e7c1cd\">Bulleted list</a></li><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"8d91fffd-e2dc-4de6-ae8c-b09b28534c34\">Straightforward components</a></li><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"5b48bc62-b13c-494a-8354-033e15ae845b\">Jump link</a></li></ul> <div class=\"nw_options_end\"></div></div>";
        String secondaryButton = "<div onclick=\"window.inqFrame.Application.sendVALinkClicked(event);\">Vanaf 6 september kunnen clubs en verenigingen zich aanmelden voor Rabo ClubSupport. De clubs die mee kunnen doen, ontvangen vanzelf een uitnodiging.<br /><br />De stembussen gaan op 4 oktober open voor alle Rabobank-leden.<br /><button><a href=\"https://www.rabobank.nl/particulieren/leden/clubsupport/\" target=\"_blank\" data-vtz-browse=\"https://www.rabobank.nl/particulieren/leden/clubsupport/\" data-vtz-link-type=\"Web\" rel=\"noopener noreferrer\">Meer over ClubSupport</a></button><blockquote style=\"margin: 0 0 0 40px; border: none; padding: 0px;\"><button><a href=\"https://bankieren.rabobank.nl/bankierenplus/deeplinking/membership-subscription/start\" target=\"_blank\" data-vtz-browse=\"https://bankieren.rabobank.nl/bankierenplus/deeplinking/membership-subscription/start\" data-vtz-link-type=\"Web\" rel=\"noopener noreferrer\">Word Lid</a></button></blockquote> \n<hr />Heb je zo een antwoord op je vraag? <ul><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"83c547b6-f2ac-4af9-b2e3-552a8e5deb0c\">Ja</a></li><li><a href=\"#\" data-vtz-link-type=\"Dialog\" data-vtz-jump=\"295a9f46-6316-4d13-97df-e42a24534366\">Nee</a></li></ul> <div class=\"nw_options_end\"></div></div>";
        System.out.println(" \n ---- Mark Down ---- \n");
        System.out.println(MarkDownConverter.convertHtmlToMarkDown(secondaryButton));
    }
}
